version: '3'

vars:
  GO_VERSION: '1.24'
  GOLANGCI_LINT_VERSION: 'v2.1.5'
  GCI_VERSION: 'v0.13.6'
  GOFUMPT_VERSION: 'v0.8.0'
  BUF_VERSION: '1.53.0'
  PROTOC_GEN_GO_VERSION: 'v1.36.6'
  PROTOC_GEN_GO_GRPC_VERSION: 'v1.5.1'
  OGEN_VERSION: 'v1.12.0'
  YQ_VERSION: 'v4.45.2'
  GRPCURL_VERSION: 'v1.9.3'

  BIN_DIR: '{{.ROOT_DIR}}/bin'
  GOLANGCI_LINT: '{{.BIN_DIR}}/golangci-lint'
  GCI: '{{.BIN_DIR}}/gci'
  GOFUMPT: '–{{.BIN_DIR}}/gofumpt'
  BUF: '{{.BIN_DIR}}/buf'
  OGEN: '{{.BIN_DIR}}/ogen'
  YQ: '{{.BIN_DIR}}/yq'
  PROTOC_GEN_GO: '{{.BIN_DIR}}/protoc-gen-go'
  PROTOC_GEN_GO_GRPC: '{{.BIN_DIR}}/protoc-gen-go-grpc'
  GRPCURL: '{{.BIN_DIR}}/grpcurl'

tasks:
  grpcurl:install:
    desc: 'foo'
    cmds:
      - |
        [ -f {{.GRPCURL}} ] || {
         echo '📦 Устанавливаем grpcurl {{.GRPCURL_VERSION}}...'
          GOBIN={{.BIN_DIR}} go install github.com/fullstorydev/grpcurl/cmd/grpcurl@{{.GRPCURL_VERSION}}
        }
       

  install-formatters:
    desc: "Устанавливает форматтеры gci и gofumpt в ./bin"
    summary: |
      Эта задача проверяет наличие инструментов форматирования кода gofumpt и gci в директории bin.
      Если инструменты не найдены, они будут автоматически установлены с указанными версиями.
      
      Используется:
        - gofumpt: для форматирования кода Go
        - gci: для сортировки импортов Go
    cmds:
      - |
        [ -f {{.GOFUMPT}} ] || {
          echo '📦 Устанавливаем gofumpt {{.GOFUMPT_VERSION}}...'
          GOBIN={{.BIN_DIR}} go install mvdan.cc/gofumpt@{{.GOFUMPT_VERSION}}
        }
        [ -f {{.GCI}} ] || {
          echo '📦 Устанавливаем gci {{.GCI_VERSION}}...'
          GOBIN={{.BIN_DIR}} go install github.com/daixiang0/gci@{{.GCI_VERSION}}
        }
    status:
      - test -x {{.GOFUMPT}}
      - test -x {{.GCI}}
  
  install-buf:
    desc: "Устанавливает Buf в каталог bin"
    cmds:
      - |
        [ -f {{.BUF}} ] || {
          mkdir -p {{.BIN_DIR}}
          curl -sSL \
            "https://github.com/bufbuild/buf/releases/download/v{{.BUF_VERSION}}/buf-$(uname -s)-$(uname -m).tar.gz" \
            | tar -xz -O buf/bin/buf > {{.BUF}}
          chmod +x {{.BUF}}
        }
  
  proto:install-plugins:
    desc: "Устанавливает protoc плагины в каталог bin"
    cmds:
      - |
        [ -f {{.PROTOC_GEN_GO}} ] || {
          echo '📦 Installing protoc-gen-go...'
          GOBIN={{.BIN_DIR}} go install google.golang.org/protobuf/cmd/protoc-gen-go@{{.PROTOC_GEN_GO_VERSION}}
        }
        [ -f {{.PROTOC_GEN_GO_GRPC}} ] || {
          echo '📦 Installing protoc-gen-go-grpc...'
          GOBIN={{.BIN_DIR}} go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@{{.PROTOC_GEN_GO_GRPC_VERSION}}
        }

  proto:gen:
    deps: [ install-buf, proto:install-plugins, proto:lint ]
    desc: Генерация Go-кода из .proto
    dir: shared/proto
    cmds:
      - '{{.BUF}} generate'

  proto:lint:
    deps: [ install-buf, proto:install-plugins ]
    desc: Проверка .proto-файлов на соответствие стилю
    dir: shared/proto
    cmds:
      - '{{.BUF}} lint'

  ogen:gen:
    desc: "Генерация Go-кода из всех OpenAPI-деклараций с x-ogen"
    deps: [ ogen:install, yq:install ]
    cmds:
      - task: redocly-cli:bundle
      - |
        find {{.OPEN_API_FILES}} -name '*.yaml' -o -name '*.yml' | while read -r file; do
          if [ -f "$file" ] && grep -q 'x-ogen:' "$file"; then
            echo "🚀 Generating from: $file"
            target=$({{.YQ}} e '."x-ogen".target' "$file")
            package=$({{.YQ}} e '."x-ogen".package' "$file")
            echo "📁 Target: $target"
            echo "📦 Package: $package"
            {{.OGEN}} \
              --target "$target" \
              --package "$package" \
              --clean \
              "$file" || exit 1
          fi
        done


  ogen:install:
    desc: "Скачивает ogen в папку bin"
    cmds:
      - |
        [ -f {{.OGEN}} ] || {
          mkdir -p {{.BIN_DIR}}
          GOBIN={{.BIN_DIR}} go install github.com/ogen-go/ogen/cmd/ogen@{{.OGEN_VERSION}}
        }

  gen:
    desc: "Генерация всех proto и OpenAPI деклараций"
    cmds:
      - task: proto:gen
      - task: ogen:gen