syntax = "proto3";

package inventory.v1;

import "google/protobuf/timestamp.proto";

option go_package = "github.com/YuryXVX/rocket-fabric/shared/pkg/proto/inventory/v1;inventory_v1";

// InventoryService предоставляет API для поиска деталей
service InventoryService {
    // Ищет деталь по UUID
    rpc GetPart(GetPartRequest) returns (GetPartResponse);
}

// Параметры запроса GetPart 
message GetPartRequest {
    // Идентификатор детали
    string uuid = 1;
}
// Ответ GetPart 
message GetPartResponse {
    // Список найденных деталей
    repeated Part parts = 1;
}

// Структура Part
message Part {
    // Уникальный идентификатор детали
    string uuid = 1;
    // Название детали
    string name = 2;
    // Описание детали
    string description = 3;
    // Цена за единицу
    double price = 4;
    // Количество на складе
    int64 stock_quantity = 5;
    // Теги для быстрого поиска
    repeated string tags = 6;
    // Категория
    Category category = 7;
    // Размеры детали 
    Dimensions dimensions = 8;
    // Информация о производителе
    Manufacturer manufacturer = 9;
    // metadata
    map<string, Value> metadata = 10;
    // Дата создания
    google.protobuf.Timestamp created_at = 11;
    
    // Дата обновления
    google.protobuf.Timestamp updated_at = 12;
}
// Category of Part
enum Category {
    // Неизвестный способ 
    CATEGORY_UNSPECIFIED = 0;
    // Двигатель
    CATEGORY_ENGINE = 1;
    // Топливо
    CATEGORY_FUEL = 2;
    // Иллюминатор
    CATEGORY_PORTHOLE = 3;
    // Крыло
    CATEGORY_WING = 4;
}

// скруктура Dimensions
message Dimensions {
    // Длина в см
    double length = 1;
    // Ширина в см
    double width = 2;
    // Высота в см
    double height = 3;
    // Вес в кг
    double weight = 4;
}


// скруктура  Manufacturer
message Manufacturer {
    // Название
    string name = 1;
    // Страна производства
    string country = 2;
    // Сайт производителя
    string website = 3;
}

// Value представляет собой union-тип для хранения различных типов данных в metadata
message Value {
  oneof kind {
    //  Строковое значение
    string string_value = 1;
    //  Целое значение 
    int64 int64_value = 2;
    // Дробное значение 
    double double_value = 3;
    // Логическое значение 
    bool bool_value = 4;
  }
}