// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: inventory/v1/inventory.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PartService_GetPartByUUID_FullMethodName = "/inventory.v1.PartService/GetPartByUUID"
	PartService_ListParts_FullMethodName     = "/inventory.v1.PartService/ListParts"
)

// PartServiceClient is the client API for PartService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PartServiceClient interface {
	// Возвращает информацию о детали по её UUID.
	//
	// Ошибки:
	// - NOT_FOUND: Деталь с таким UUID не найдена
	// - INVALID_ARGUMENT: Некорректный формат UUID
	GetPartByUUID(ctx context.Context, in *GetPartByUUIDRequest, opts ...grpc.CallOption) (*GetPartByUUIDResponse, error)
	// Возвращает список деталей с возможностью фильтрации по типу или по конкретным UUID.
	//
	// Ошибки:
	// - NOT_FOUND: Одна или несколько деталей из uuids не найдены
	// - INVALID_ARGUMENT: Невалидный формат UUID в списке uuids
	ListParts(ctx context.Context, in *ListPartsRequest, opts ...grpc.CallOption) (*ListPartsResponse, error)
}

type partServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPartServiceClient(cc grpc.ClientConnInterface) PartServiceClient {
	return &partServiceClient{cc}
}

func (c *partServiceClient) GetPartByUUID(ctx context.Context, in *GetPartByUUIDRequest, opts ...grpc.CallOption) (*GetPartByUUIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPartByUUIDResponse)
	err := c.cc.Invoke(ctx, PartService_GetPartByUUID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partServiceClient) ListParts(ctx context.Context, in *ListPartsRequest, opts ...grpc.CallOption) (*ListPartsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPartsResponse)
	err := c.cc.Invoke(ctx, PartService_ListParts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PartServiceServer is the server API for PartService service.
// All implementations must embed UnimplementedPartServiceServer
// for forward compatibility.
type PartServiceServer interface {
	// Возвращает информацию о детали по её UUID.
	//
	// Ошибки:
	// - NOT_FOUND: Деталь с таким UUID не найдена
	// - INVALID_ARGUMENT: Некорректный формат UUID
	GetPartByUUID(context.Context, *GetPartByUUIDRequest) (*GetPartByUUIDResponse, error)
	// Возвращает список деталей с возможностью фильтрации по типу или по конкретным UUID.
	//
	// Ошибки:
	// - NOT_FOUND: Одна или несколько деталей из uuids не найдены
	// - INVALID_ARGUMENT: Невалидный формат UUID в списке uuids
	ListParts(context.Context, *ListPartsRequest) (*ListPartsResponse, error)
	mustEmbedUnimplementedPartServiceServer()
}

// UnimplementedPartServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPartServiceServer struct{}

func (UnimplementedPartServiceServer) GetPartByUUID(context.Context, *GetPartByUUIDRequest) (*GetPartByUUIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPartByUUID not implemented")
}
func (UnimplementedPartServiceServer) ListParts(context.Context, *ListPartsRequest) (*ListPartsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListParts not implemented")
}
func (UnimplementedPartServiceServer) mustEmbedUnimplementedPartServiceServer() {}
func (UnimplementedPartServiceServer) testEmbeddedByValue()                     {}

// UnsafePartServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PartServiceServer will
// result in compilation errors.
type UnsafePartServiceServer interface {
	mustEmbedUnimplementedPartServiceServer()
}

func RegisterPartServiceServer(s grpc.ServiceRegistrar, srv PartServiceServer) {
	// If the following call panics, it indicates UnimplementedPartServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PartService_ServiceDesc, srv)
}

func _PartService_GetPartByUUID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPartByUUIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartServiceServer).GetPartByUUID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartService_GetPartByUUID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartServiceServer).GetPartByUUID(ctx, req.(*GetPartByUUIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartService_ListParts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPartsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartServiceServer).ListParts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartService_ListParts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartServiceServer).ListParts(ctx, req.(*ListPartsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PartService_ServiceDesc is the grpc.ServiceDesc for PartService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PartService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "inventory.v1.PartService",
	HandlerType: (*PartServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPartByUUID",
			Handler:    _PartService_GetPartByUUID_Handler,
		},
		{
			MethodName: "ListParts",
			Handler:    _PartService_ListParts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "inventory/v1/inventory.proto",
}
