// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: inventory/v1/inventory.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// enum тип детали
type PartType int32

const (
	// Не указан (дефолтное значение)
	PartType_PART_TYPE_UNSPECIFIED PartType = 0
	// Корпус корабля
	PartType_PART_TYPE_HULL PartType = 1
	// Двигатель
	PartType_PART_TYPE_ENGINE PartType = 2
	// Защитный щит
	PartType_PART_TYPE_SHIELD PartType = 3
	// Вооружение
	PartType_PART_TYPE_WEAPON PartType = 4
)

// Enum value maps for PartType.
var (
	PartType_name = map[int32]string{
		0: "PART_TYPE_UNSPECIFIED",
		1: "PART_TYPE_HULL",
		2: "PART_TYPE_ENGINE",
		3: "PART_TYPE_SHIELD",
		4: "PART_TYPE_WEAPON",
	}
	PartType_value = map[string]int32{
		"PART_TYPE_UNSPECIFIED": 0,
		"PART_TYPE_HULL":        1,
		"PART_TYPE_ENGINE":      2,
		"PART_TYPE_SHIELD":      3,
		"PART_TYPE_WEAPON":      4,
	}
)

func (x PartType) Enum() *PartType {
	p := new(PartType)
	*p = x
	return p
}

func (x PartType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PartType) Descriptor() protoreflect.EnumDescriptor {
	return file_inventory_v1_inventory_proto_enumTypes[0].Descriptor()
}

func (PartType) Type() protoreflect.EnumType {
	return &file_inventory_v1_inventory_proto_enumTypes[0]
}

func (x PartType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PartType.Descriptor instead.
func (PartType) EnumDescriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{0}
}

// Запрос для получения списка деталей
type ListPartsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Фильтр по типу. Если передано PART_TYPE_UNSPECIFIED, фильтр по типу игнорируется (все детали).
	PartType PartType `protobuf:"varint,1,opt,name=part_type,json=partType,proto3,enum=inventory.v1.PartType" json:"part_type,omitempty"`
	// Опционально: конкретные UUID. Имеет приоритет над part_type.
	// В proto3 массивы задаются ключевым словом repeated.
	Uuids         []string `protobuf:"bytes,2,rep,name=uuids,proto3" json:"uuids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPartsRequest) Reset() {
	*x = ListPartsRequest{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPartsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPartsRequest) ProtoMessage() {}

func (x *ListPartsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPartsRequest.ProtoReflect.Descriptor instead.
func (*ListPartsRequest) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *ListPartsRequest) GetPartType() PartType {
	if x != nil {
		return x.PartType
	}
	return PartType_PART_TYPE_UNSPECIFIED
}

func (x *ListPartsRequest) GetUuids() []string {
	if x != nil {
		return x.Uuids
	}
	return nil
}

// Ответ со списком деталей
type ListPartsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Список найденных деталей
	Parts         []*Part `protobuf:"bytes,1,rep,name=parts,proto3" json:"parts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPartsResponse) Reset() {
	*x = ListPartsResponse{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPartsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPartsResponse) ProtoMessage() {}

func (x *ListPartsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPartsResponse.ProtoReflect.Descriptor instead.
func (*ListPartsResponse) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *ListPartsResponse) GetParts() []*Part {
	if x != nil {
		return x.Parts
	}
	return nil
}

// Запрос получения детали
type GetPartByUUIDRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Идентификатор детали
	Uuid          string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPartByUUIDRequest) Reset() {
	*x = GetPartByUUIDRequest{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPartByUUIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPartByUUIDRequest) ProtoMessage() {}

func (x *GetPartByUUIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPartByUUIDRequest.ProtoReflect.Descriptor instead.
func (*GetPartByUUIDRequest) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{2}
}

func (x *GetPartByUUIDRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

// Ответ с информацией о детали
type GetPartByUUIDResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Информация о детали
	Part          *Part `protobuf:"bytes,1,opt,name=part,proto3" json:"part,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPartByUUIDResponse) Reset() {
	*x = GetPartByUUIDResponse{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPartByUUIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPartByUUIDResponse) ProtoMessage() {}

func (x *GetPartByUUIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPartByUUIDResponse.ProtoReflect.Descriptor instead.
func (*GetPartByUUIDResponse) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{3}
}

func (x *GetPartByUUIDResponse) GetPart() *Part {
	if x != nil {
		return x.Part
	}
	return nil
}

// Информация о детали
type Part struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// uuid уникальный идентификатор детали
	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	// name назавние детали
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// description oписание детали
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// price цена в копейках  (5000₽ = 500000)
	Price int64 `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	// stock_quantity количество на складе
	StockQuantity int64 `protobuf:"varint,5,opt,name=stock_quantity,json=stockQuantity,proto3" json:"stock_quantity,omitempty"`
	// created_at дата создания
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// part_type тип детали (enum)
	PartType      PartType `protobuf:"varint,7,opt,name=part_type,json=partType,proto3,enum=inventory.v1.PartType" json:"part_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Part) Reset() {
	*x = Part{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Part) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Part) ProtoMessage() {}

func (x *Part) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Part.ProtoReflect.Descriptor instead.
func (*Part) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{4}
}

func (x *Part) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Part) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Part) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Part) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Part) GetStockQuantity() int64 {
	if x != nil {
		return x.StockQuantity
	}
	return 0
}

func (x *Part) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Part) GetPartType() PartType {
	if x != nil {
		return x.PartType
	}
	return PartType_PART_TYPE_UNSPECIFIED
}

type ValidateCompatibilityRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UUID детали в слоте корпуса (обязательный слот)
	HullUuid string `protobuf:"bytes,1,opt,name=hull_uuid,json=hullUuid,proto3" json:"hull_uuid,omitempty"`
	// UUID детали в слоте двигателя (обязательный слот)
	EngineUuid string `protobuf:"bytes,2,opt,name=engine_uuid,json=engineUuid,proto3" json:"engine_uuid,omitempty"`
	// UUID детали в слоте щита (опциональный слот, пустая строка — слот не используется)
	ShieldUuid string `protobuf:"bytes,3,opt,name=shield_uuid,json=shieldUuid,proto3" json:"shield_uuid,omitempty"`
	// UUID детали в слоте оружия (опциональный слот, пустая строка — слот не используется)
	WeaponUuid    string `protobuf:"bytes,4,opt,name=weapon_uuid,json=weaponUuid,proto3" json:"weapon_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateCompatibilityRequest) Reset() {
	*x = ValidateCompatibilityRequest{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateCompatibilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateCompatibilityRequest) ProtoMessage() {}

func (x *ValidateCompatibilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateCompatibilityRequest.ProtoReflect.Descriptor instead.
func (*ValidateCompatibilityRequest) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{5}
}

func (x *ValidateCompatibilityRequest) GetHullUuid() string {
	if x != nil {
		return x.HullUuid
	}
	return ""
}

func (x *ValidateCompatibilityRequest) GetEngineUuid() string {
	if x != nil {
		return x.EngineUuid
	}
	return ""
}

func (x *ValidateCompatibilityRequest) GetShieldUuid() string {
	if x != nil {
		return x.ShieldUuid
	}
	return ""
}

func (x *ValidateCompatibilityRequest) GetWeaponUuid() string {
	if x != nil {
		return x.WeaponUuid
	}
	return ""
}

// Ответ на проверку совместимости (пустой — значит совместимы)
type ValidateCompatibilityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateCompatibilityResponse) Reset() {
	*x = ValidateCompatibilityResponse{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateCompatibilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateCompatibilityResponse) ProtoMessage() {}

func (x *ValidateCompatibilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateCompatibilityResponse.ProtoReflect.Descriptor instead.
func (*ValidateCompatibilityResponse) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{6}
}

// Запрос на резервирование деталей
type ReservePartsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UUID деталей для резервирования
	Uuids         []string `protobuf:"bytes,1,rep,name=uuids,proto3" json:"uuids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReservePartsRequest) Reset() {
	*x = ReservePartsRequest{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReservePartsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReservePartsRequest) ProtoMessage() {}

func (x *ReservePartsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReservePartsRequest.ProtoReflect.Descriptor instead.
func (*ReservePartsRequest) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{7}
}

func (x *ReservePartsRequest) GetUuids() []string {
	if x != nil {
		return x.Uuids
	}
	return nil
}

// Ответ на резервирование (пустой — значит успешно)
type ReservePartsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReservePartsResponse) Reset() {
	*x = ReservePartsResponse{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReservePartsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReservePartsResponse) ProtoMessage() {}

func (x *ReservePartsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReservePartsResponse.ProtoReflect.Descriptor instead.
func (*ReservePartsResponse) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{8}
}

// Запрос на освобождение ранее зарезервированных деталей
type ReleasePartsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UUID деталей для освобождения
	Uuids         []string `protobuf:"bytes,1,rep,name=uuids,proto3" json:"uuids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleasePartsRequest) Reset() {
	*x = ReleasePartsRequest{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleasePartsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleasePartsRequest) ProtoMessage() {}

func (x *ReleasePartsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleasePartsRequest.ProtoReflect.Descriptor instead.
func (*ReleasePartsRequest) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{9}
}

func (x *ReleasePartsRequest) GetUuids() []string {
	if x != nil {
		return x.Uuids
	}
	return nil
}

// Ответ на освобождение (пустой — значит успешно)
type ReleasePartsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleasePartsResponse) Reset() {
	*x = ReleasePartsResponse{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleasePartsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleasePartsResponse) ProtoMessage() {}

func (x *ReleasePartsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleasePartsResponse.ProtoReflect.Descriptor instead.
func (*ReleasePartsResponse) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{10}
}

var File_inventory_v1_inventory_proto protoreflect.FileDescriptor

const file_inventory_v1_inventory_proto_rawDesc = "" +
	"\n" +
	"\x1cinventory/v1/inventory.proto\x12\finventory.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"]\n" +
	"\x10ListPartsRequest\x123\n" +
	"\tpart_type\x18\x01 \x01(\x0e2\x16.inventory.v1.PartTypeR\bpartType\x12\x14\n" +
	"\x05uuids\x18\x02 \x03(\tR\x05uuids\"=\n" +
	"\x11ListPartsResponse\x12(\n" +
	"\x05parts\x18\x01 \x03(\v2\x12.inventory.v1.PartR\x05parts\"*\n" +
	"\x14GetPartByUUIDRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"?\n" +
	"\x15GetPartByUUIDResponse\x12&\n" +
	"\x04part\x18\x01 \x01(\v2\x12.inventory.v1.PartR\x04part\"\xfd\x01\n" +
	"\x04Part\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x03R\x05price\x12%\n" +
	"\x0estock_quantity\x18\x05 \x01(\x03R\rstockQuantity\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x123\n" +
	"\tpart_type\x18\a \x01(\x0e2\x16.inventory.v1.PartTypeR\bpartType\"\x9e\x01\n" +
	"\x1cValidateCompatibilityRequest\x12\x1b\n" +
	"\thull_uuid\x18\x01 \x01(\tR\bhullUuid\x12\x1f\n" +
	"\vengine_uuid\x18\x02 \x01(\tR\n" +
	"engineUuid\x12\x1f\n" +
	"\vshield_uuid\x18\x03 \x01(\tR\n" +
	"shieldUuid\x12\x1f\n" +
	"\vweapon_uuid\x18\x04 \x01(\tR\n" +
	"weaponUuid\"\x1f\n" +
	"\x1dValidateCompatibilityResponse\"+\n" +
	"\x13ReservePartsRequest\x12\x14\n" +
	"\x05uuids\x18\x01 \x03(\tR\x05uuids\"\x16\n" +
	"\x14ReservePartsResponse\"+\n" +
	"\x13ReleasePartsRequest\x12\x14\n" +
	"\x05uuids\x18\x01 \x03(\tR\x05uuids\"\x16\n" +
	"\x14ReleasePartsResponse*{\n" +
	"\bPartType\x12\x19\n" +
	"\x15PART_TYPE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0ePART_TYPE_HULL\x10\x01\x12\x14\n" +
	"\x10PART_TYPE_ENGINE\x10\x02\x12\x14\n" +
	"\x10PART_TYPE_SHIELD\x10\x03\x12\x14\n" +
	"\x10PART_TYPE_WEAPON\x10\x042\xd5\x03\n" +
	"\vPartService\x12X\n" +
	"\rGetPartByUUID\x12\".inventory.v1.GetPartByUUIDRequest\x1a#.inventory.v1.GetPartByUUIDResponse\x12L\n" +
	"\tListParts\x12\x1e.inventory.v1.ListPartsRequest\x1a\x1f.inventory.v1.ListPartsResponse\x12p\n" +
	"\x15ValidateCompatibility\x12*.inventory.v1.ValidateCompatibilityRequest\x1a+.inventory.v1.ValidateCompatibilityResponse\x12U\n" +
	"\fReserveParts\x12!.inventory.v1.ReservePartsRequest\x1a\".inventory.v1.ReservePartsResponse\x12U\n" +
	"\fReleaseParts\x12!.inventory.v1.ReleasePartsRequest\x1a\".inventory.v1.ReleasePartsResponseB\x1fZ\x1dshared/pkg/proto/inventory/v1b\x06proto3"

var (
	file_inventory_v1_inventory_proto_rawDescOnce sync.Once
	file_inventory_v1_inventory_proto_rawDescData []byte
)

func file_inventory_v1_inventory_proto_rawDescGZIP() []byte {
	file_inventory_v1_inventory_proto_rawDescOnce.Do(func() {
		file_inventory_v1_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_inventory_v1_inventory_proto_rawDesc), len(file_inventory_v1_inventory_proto_rawDesc)))
	})
	return file_inventory_v1_inventory_proto_rawDescData
}

var file_inventory_v1_inventory_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_inventory_v1_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_inventory_v1_inventory_proto_goTypes = []any{
	(PartType)(0),                         // 0: inventory.v1.PartType
	(*ListPartsRequest)(nil),              // 1: inventory.v1.ListPartsRequest
	(*ListPartsResponse)(nil),             // 2: inventory.v1.ListPartsResponse
	(*GetPartByUUIDRequest)(nil),          // 3: inventory.v1.GetPartByUUIDRequest
	(*GetPartByUUIDResponse)(nil),         // 4: inventory.v1.GetPartByUUIDResponse
	(*Part)(nil),                          // 5: inventory.v1.Part
	(*ValidateCompatibilityRequest)(nil),  // 6: inventory.v1.ValidateCompatibilityRequest
	(*ValidateCompatibilityResponse)(nil), // 7: inventory.v1.ValidateCompatibilityResponse
	(*ReservePartsRequest)(nil),           // 8: inventory.v1.ReservePartsRequest
	(*ReservePartsResponse)(nil),          // 9: inventory.v1.ReservePartsResponse
	(*ReleasePartsRequest)(nil),           // 10: inventory.v1.ReleasePartsRequest
	(*ReleasePartsResponse)(nil),          // 11: inventory.v1.ReleasePartsResponse
	(*timestamppb.Timestamp)(nil),         // 12: google.protobuf.Timestamp
}
var file_inventory_v1_inventory_proto_depIdxs = []int32{
	0,  // 0: inventory.v1.ListPartsRequest.part_type:type_name -> inventory.v1.PartType
	5,  // 1: inventory.v1.ListPartsResponse.parts:type_name -> inventory.v1.Part
	5,  // 2: inventory.v1.GetPartByUUIDResponse.part:type_name -> inventory.v1.Part
	12, // 3: inventory.v1.Part.created_at:type_name -> google.protobuf.Timestamp
	0,  // 4: inventory.v1.Part.part_type:type_name -> inventory.v1.PartType
	3,  // 5: inventory.v1.PartService.GetPartByUUID:input_type -> inventory.v1.GetPartByUUIDRequest
	1,  // 6: inventory.v1.PartService.ListParts:input_type -> inventory.v1.ListPartsRequest
	6,  // 7: inventory.v1.PartService.ValidateCompatibility:input_type -> inventory.v1.ValidateCompatibilityRequest
	8,  // 8: inventory.v1.PartService.ReserveParts:input_type -> inventory.v1.ReservePartsRequest
	10, // 9: inventory.v1.PartService.ReleaseParts:input_type -> inventory.v1.ReleasePartsRequest
	4,  // 10: inventory.v1.PartService.GetPartByUUID:output_type -> inventory.v1.GetPartByUUIDResponse
	2,  // 11: inventory.v1.PartService.ListParts:output_type -> inventory.v1.ListPartsResponse
	7,  // 12: inventory.v1.PartService.ValidateCompatibility:output_type -> inventory.v1.ValidateCompatibilityResponse
	9,  // 13: inventory.v1.PartService.ReserveParts:output_type -> inventory.v1.ReservePartsResponse
	11, // 14: inventory.v1.PartService.ReleaseParts:output_type -> inventory.v1.ReleasePartsResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_inventory_v1_inventory_proto_init() }
func file_inventory_v1_inventory_proto_init() {
	if File_inventory_v1_inventory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_inventory_v1_inventory_proto_rawDesc), len(file_inventory_v1_inventory_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inventory_v1_inventory_proto_goTypes,
		DependencyIndexes: file_inventory_v1_inventory_proto_depIdxs,
		EnumInfos:         file_inventory_v1_inventory_proto_enumTypes,
		MessageInfos:      file_inventory_v1_inventory_proto_msgTypes,
	}.Build()
	File_inventory_v1_inventory_proto = out.File
	file_inventory_v1_inventory_proto_goTypes = nil
	file_inventory_v1_inventory_proto_depIdxs = nil
}
